<a href="https://colab.research.google.com/github/Anshika91/GPU_Management_For_DeepLearning/blob/main/Tensorflow3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ragged Array. and Ragged Tensors


In [1]:
import numpy as np

In [5]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11]])

<ipython-input-5-e9f03e10e52e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11]])


In [6]:
x

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9]), list([10, 11])],
      dtype=object)

In [9]:
# Ragged array A special kind of array that represents a list of arrays of differenet siz., it is a tensor with one or more ragged dimensions.
import tensorflow as tf
tf.constant([1.,2,3],[4.,5,6.,7.]) # Not able 
r1=tf.ragged.constant([[65,66],[],[67]])

In [10]:
r2=tf.ragged.constant([[67,97,102,233],[67,111,102,102,101,101],[99,97,102,102,232],[21654,21857]])

In [23]:
r3=tf.concat([r1,r2],axis=0)

In [13]:
r3.shape  # r3 shape is tensor shape.

TensorShape([7, None])

In [33]:
r4=tf.ragged.constant([[1,2,3],[4]])

In [34]:
r5=tf.ragged.constant([[5,6],[7,8,3]])

In [35]:
tf.concat([r4,r5],axis=0)

<tf.RaggedTensor [[1, 2, 3], [4], [5, 6], [7, 8, 3]]>

In [36]:
tf.concat([r4,r5],axis=1)

<tf.RaggedTensor [[1, 2, 3, 5, 6], [4, 7, 8, 3]]>

In [37]:
r6=tf.ragged.constant([[5,6],[7,8,9,10]])

In [38]:
tf.concat([r4,r6],axis=0)

<tf.RaggedTensor [[1, 2, 3], [4], [5, 6], [7, 8, 9, 10]]>

In [39]:
tf.concat([r4,r6],axis=1)

<tf.RaggedTensor [[1, 2, 3, 5, 6],
 [4, 7, 8, 9, 10]]>

In [44]:
r7=tf.ragged.constant([[1,2],[3,4],[5]])
r8=tf.ragged.constant([[7],[],[9,10,11]])

In [45]:
tf.concat([r7,r8],axis=0)

<tf.RaggedTensor [[1, 2], [3, 4], [5], [7], [], [9, 10, 11]]>

In [46]:
tf.concat([r7,r8],axis=1)

<tf.RaggedTensor [[1, 2, 7], [3, 4], [5, 9, 10, 11]]>

In [51]:
r8=tf.ragged.constant([[7],[],[9,10,11],[12,13]])

In [52]:
r8

<tf.RaggedTensor [[7], [], [9, 10, 11], [12, 13]]>

In [53]:
r8.to_tensor()

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7,  0,  0],
       [ 0,  0,  0],
       [ 9, 10, 11],
       [12, 13,  0]], dtype=int32)>

In [54]:
r8.to_tensor(default_value=5)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7,  5,  5],
       [ 5,  5,  5],
       [ 9, 10, 11],
       [12, 13,  5]], dtype=int32)>